name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-server-1:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server 1 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd urban-brew-cafe
            git pull
            cp index.html /var/www/html/index.html

  deploy-server-2:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server 2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd urban-brew-cafe
            git pull
            cp index.html /var/www/html/index.html